name: Generate PDF and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Runs the workflow when changes are pushed to the main branch

jobs:
  generate_pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install  gspread google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client reportlab

      - name: Run Python script to generate PDF
        env:
            GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE }}
            FOLDER_ID: ${{ secrets.FOLDER_ID }}
        run: python main.py

      - name: Move PDF to GitHub Pages directory
        run: |
          mkdir -p pdf
          mv output.pdf pdf/

      - name: Generate list of PDFs and update README.md
        run: |
          # Generate the list of PDF links
          pdf_list=$(find pdf -name "*.pdf" | awk '{print "- [" $1 "](" $1 ")"}')
          # Insert the list into README.md
          sed -i '/<!-- PDF-LIST-START -->/,/<!-- PDF-LIST-END -->/c\<!-- PDF-LIST-START -->\n'"$pdf_list"'\n<!-- PDF-LIST-END -->' README.md

      - name: Commit and push generated PDF to GitHub Pages
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add README.md pdf/*.pdf
          git commit -m "Add generated PDF"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
