name: Generate PDF and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Runs the workflow when changes are pushed to the main branch

jobs:
  generate_pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install  gspread google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client reportlab genanki

      - name: Run Python script to generate PDF
        env:
            GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE }}
            FOLDER_ID: ${{ secrets.FOLDER_ID }}
        run: python main.py

      - name: Move PDF to GitHub Pages directory
        run: |
          mkdir -p pdf
          if compgen -G "*.pdf" > /dev/null; then
            mv *.pdf pdf/
          fi

          mkdir -p anki
          if compgen -G "*.apkg" > /dev/null; then
            mv *.apkg anki/
          fi
          if compgen -G "*.csv" > /dev/null; then
            mv *.csv anki/
          fi

      - name: Commit and push generated PDF to GitHub Pages
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add README.md pdf/*.pdf anki/* misc/update_guard.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "[JOB] Update files"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
